/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTokenRouteImport } from './routes/t/$token'
import { Route as AuthenticatedTablesRouteImport } from './routes/_authenticated/tables'
import { Route as AuthenticatedOpsRouteImport } from './routes/_authenticated/ops'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedKdsRouteImport } from './routes/_authenticated/kds'
import { Route as AuthenticatedIntelRouteImport } from './routes/_authenticated/intel'
import { Route as AuthenticatedHostRouteImport } from './routes/_authenticated/host'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as TTokenOrderOrderIdRouteImport } from './routes/t/$token.order.$orderId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTablesRoute = AuthenticatedTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpsRoute = AuthenticatedOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKdsRoute = AuthenticatedKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelRoute = AuthenticatedIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostRoute = AuthenticatedHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TTokenOrderOrderIdRoute = TTokenOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => TTokenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/host': typeof AuthenticatedHostRoute
  '/intel': typeof AuthenticatedIntelRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/ops': typeof AuthenticatedOpsRoute
  '/tables': typeof AuthenticatedTablesRoute
  '/t/$token': typeof TTokenRouteWithChildren
  '/t/$token/order/$orderId': typeof TTokenOrderOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/host': typeof AuthenticatedHostRoute
  '/intel': typeof AuthenticatedIntelRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/ops': typeof AuthenticatedOpsRoute
  '/tables': typeof AuthenticatedTablesRoute
  '/t/$token': typeof TTokenRouteWithChildren
  '/t/$token/order/$orderId': typeof TTokenOrderOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/host': typeof AuthenticatedHostRoute
  '/_authenticated/intel': typeof AuthenticatedIntelRoute
  '/_authenticated/kds': typeof AuthenticatedKdsRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/ops': typeof AuthenticatedOpsRoute
  '/_authenticated/tables': typeof AuthenticatedTablesRoute
  '/t/$token': typeof TTokenRouteWithChildren
  '/t/$token/order/$orderId': typeof TTokenOrderOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/host'
    | '/intel'
    | '/kds'
    | '/menu'
    | '/ops'
    | '/tables'
    | '/t/$token'
    | '/t/$token/order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/host'
    | '/intel'
    | '/kds'
    | '/menu'
    | '/ops'
    | '/tables'
    | '/t/$token'
    | '/t/$token/order/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/host'
    | '/_authenticated/intel'
    | '/_authenticated/kds'
    | '/_authenticated/menu'
    | '/_authenticated/ops'
    | '/_authenticated/tables'
    | '/t/$token'
    | '/t/$token/order/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TTokenRoute: typeof TTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tables': {
      id: '/_authenticated/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof AuthenticatedTablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops': {
      id: '/_authenticated/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof AuthenticatedOpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kds': {
      id: '/_authenticated/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof AuthenticatedKdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intel': {
      id: '/_authenticated/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof AuthenticatedIntelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host': {
      id: '/_authenticated/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AuthenticatedHostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/t/$token/order/$orderId': {
      id: '/t/$token/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/t/$token/order/$orderId'
      preLoaderRoute: typeof TTokenOrderOrderIdRouteImport
      parentRoute: typeof TTokenRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHostRoute: typeof AuthenticatedHostRoute
  AuthenticatedIntelRoute: typeof AuthenticatedIntelRoute
  AuthenticatedKdsRoute: typeof AuthenticatedKdsRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedOpsRoute: typeof AuthenticatedOpsRoute
  AuthenticatedTablesRoute: typeof AuthenticatedTablesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHostRoute: AuthenticatedHostRoute,
  AuthenticatedIntelRoute: AuthenticatedIntelRoute,
  AuthenticatedKdsRoute: AuthenticatedKdsRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedOpsRoute: AuthenticatedOpsRoute,
  AuthenticatedTablesRoute: AuthenticatedTablesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TTokenRouteChildren {
  TTokenOrderOrderIdRoute: typeof TTokenOrderOrderIdRoute
}

const TTokenRouteChildren: TTokenRouteChildren = {
  TTokenOrderOrderIdRoute: TTokenOrderOrderIdRoute,
}

const TTokenRouteWithChildren =
  TTokenRoute._addFileChildren(TTokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TTokenRoute: TTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
